### ISSUE TITLE
Wrong behaviour when integer size exceeds packing format size

### ISSUE THREAD

**Issue by henzef** [eerimoq/bitstruct#11]
See the example code:

    >>> a = bitstruct.compile(">u8<")
    >>> a.pack(255)
    b'\xff'
    >>> a.pack(256)
    b'\x00\x00'
    >>> a.pack(257)
    b'\x01\x00'
    >>> a.pack(12313521321321321)
    b'i\xa4J\x18\x15\xbfX'

I would have expected bitstruct to behave like the struct module in such a case:

    >>> import struct
    >>> struct.pack("b", 8)
    b'\x08'
    >>> struct.pack("b", 256)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    struct.error: byte format requires -128 <= number <= 127

**Comment by eerimoq** [comment]
Feel free to implement a check. I suggest checking all arguments early in the pack method.

**Comment by powerswitch** [comment]
Quick workaround:
```
data = bitstruct.pack(fmt, value)
assert len(data) == math.ceil(bitstruct.calcsize(fmt) / 8)
```

**Comment by eerimoq** [comment]
@henzef Are you working on this?

**Comment by henzef** [comment]
I am afraid not. It's just a bug I noticed and fixed by adapting the format string. It's not a high priority for me at the moment.

**Comment by eerimoq** [comment]
Integer range checks is part of version 4.0.0.

``` python
>>> import bitstruct
>>> a = bitstruct.compile("u8")
>>> a.pack(255)
b'\xff'
>>> a.pack(256)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    a.pack(256)
  File "/home/erik/workspace/bitstruct/bitstruct.py", line 300, in pack
    bits = self._pack_value(info, args[i], bits)
  File "/home/erik/workspace/bitstruct/bitstruct.py", line 257, in _pack_value
    value_bits = info.pack(value)
  File "/home/erik/workspace/bitstruct/bitstruct.py", line 71, in pack
    arg))
bitstruct.Error: "u8" requires 0 <= integer <= 255 (got 256)
>>>
```
